### ISSUE TITLE
Add test time and sample size as an option per benchmark basis in config yaml files

### ISSUE THREAD

**Issue by sidezrw** [hebench/frontend#20]
**Is your feature request related to a problem? Please describe.**  
Currently, **minimum test time** and **sample size** options are global in a yaml file. Multiple benchmarks will use the global values even if they are not appropriate for their implementation.

**Describe the solution you'd like**  
It would be nice to have a per-benchmark setting for these options (with, perhaps, sample size per operand). Maybe using the global values as fallback.

From the docs, a suggested version goes from current:

```yaml
default_min_test_time: <min_test_time_ms>
default_sample_size: <sample_size>
random_seed: <seed>

benchmark:
  - ID: <benchmark_id>
    params:
      0:
        name: <param_name>
        type: <param_type>
        value:
          from: <value_from>
          to: <value_to>
          step: <value_step>
      1:
        name: <param_name>
        type: <param_type>
        value:
          from: <value_from>
          to: <value_to>
          step: <value_step>
      ...
```

to

```yaml
default_min_test_time: <min_test_time_ms>
default_sample_size: <sample_size>
random_seed: <seed>

benchmark:
  - ID: <benchmark_id>
    default_min_test_time: <min_test_time_ms>
    default_sample_size:
      0: <sample_size_for_operand_0>
      1: <sample_size_for_operand_1>
      ...
    params:
      0:
        name: <param_name>
        type: <param_type>
        value:
          from: <value_from>
          to: <value_to>
          step: <value_step>
      1:
        name: <param_name>
        type: <param_type>
        value:
          from: <value_from>
          to: <value_to>
          step: <value_step>
      ...
```

**Describe alternatives you've considered**  
To achieve this effect currently, a user has to create a config yaml file per test they want to run.
